#!/bin/bash -eE

# A wrapper for tonos-cli
. /etc/ftn.conf
. $FNT_WRP/ftnlib

if [ -n "$1" ]; then
    case "$1" in
    $func_list) $1 ${@:1};;
	"--version") version;;
    *) echo "Command $1 not recognized. Please try to use \"help\".";;
    esac
fi

