#!/bin/bash

#########################################
#
#  Configurable part.
#  This is usually not required, but you can change something in this section.
#
#########################################

NET_NAME="net.ton.dev"
#NET_NAME="main.ton.dev"
LOG_DIR="/var/log/ftn"

shopt -s extglob
# The following variable can be used to ingnore a directory names. 
ignore_list="@(docker)"


#########################################
#
#  Please don't change anything below without a good reason
#
#########################################

# Searching for FreeTON directory
TON_DIR=$(find / -type d -name $NET_NAME -print -quit 2>/dev/null | grep -vE $ignore_list)
if [ -z "TON_DIR" ]; then
    echo "ERROR: Can't find FreeTON instalation."
    exit 1
fi

FTN_WRP=$(pwd -P)
export PATH="$FTN_WRP:$PATH"
echo "export PATH=\"$FTN_WRP:\$PATH\"" >> ~/.profile

. $TON_DIR/scripts/env.sh
#ADDR_FILE="$(hostname -s).addr"
#TON_MSIGACC=$(cat "${KEYS_DIR}/${ADDR_FILE}")

# Composing ftn config file 
#sudo bash -c "cat <<EOLONGFILE > /etc/ftn.conf
sudo cat <<EOLONGFILE > ~/ftn.conf
FTN_WRP="$FTN_WRP"
FTN_HOST="\$(hostname -s)"
FTN_ACCOUNT="\$(cat $KEYS_DIR/\$FTN_HOST.addr)"
FTN_LOG="$LOG_DIR"
FTN_KEYS_DIR="$KEYS_DIR"
FTN_DIR="$TON_DIR"
FTN_DB_DIR="$TON_WORK_DIR"
FTN_AUTO_BACKUP_KEYS="Y"
FTN_BACKUP_DIR=~
TONOS_CLI_DIR="$TON_DIR/tonos-cli/target/release"
TONOS_CLI="$TON_DIR/tonos-cli/target/release/tonos-cli"
TON_CFG_DIR="$TON_DIR/configs"
EOLONGFILE

# Handing out prmissions
chmod 755 ${FTN_WRP}/ftn
chmod 644 ${FTN_WRP}/lib/ftnlib*

# Create log dir
sudo mkdir -p $LOG_DIR
sudo chmod 755 $LOG_DIR
user=$(id -un)
group=$(id -gn)
sudo chown $user:$group $LOG_DIR
